### PR TITLE
[WIP] coverage: configure eager coverage

### PR DESCRIPTION
**Pull request by blueyed**
This should cover the plugin itself then.

### CODE REVIEW

**Comment by blueyed** [comment]
I will stop here for now.
I think we should get the other CI related PRs in first, and then it is probably better to not use pytest-cov, but coveragepy directly.

**Comment by blueyed** [comment]
No coverage for pypy (and it makes it really slow): https://travis-ci.org/Frozenball/pytest-sugar/jobs/445000743#L564

**Comment by blueyed** [comment]
Needs update after #160.
Also should address https://github.com/Frozenball/pytest-sugar/pull/160/files#diff-5205b06d924f1150750e0cc9f8326313R630.

**Comment by Teemu** [comment]
Hey 👋 

Thank you for your PR! I am going through the old PRs in this repository and closing them since a long time has passed since the opening and they may not be that relevant anymore. If you still wish to continue with this pull request, let me know and we can re-open it.

Teemu

**Pull request closed without merging**
